version: "3"

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: url-shortener-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_ADDR=db:6379
      - DB_PASS=
      - APP_PORT=:3000
      - DOMAIN=http://localhost:3000
      - API_QUOTA=10
  
  db:
    image: redis:alpine
    container_name: url-shortener-db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data